name: Flutter CI

on:
  push:
    branches:
      - main
      - feature/**
  pull_request:
    branches:
      - main

jobs:
  analyze_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Run analyzer
        run: flutter analyze

      - name: Run unit tests
        run: flutter test

      - name: Build Web
        run: |
          cd example
          flutter build web --no-pub

      - name: Build Android APK
        run: |
          cd example
          flutter build apk --debug --no-pub

  build_macos_and_ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build macOS
        run: |
          cd example
          flutter build macos --debug

      - name: Build iOS (No codesign)
        run: |
          cd example
          flutter build ios --no-codesign --debug

  build_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build Windows
        run: |
          cd example
          flutter build windows --debug
